#!/bin/bash

TEMP=$(sensors | grep -e 'Core 0' | awk '{ print $3}' | tr -d '+' | tr -d '[°C]' | awk '{ print int($1)}')
URGENT_VALUE=87

if [[ "${TEMP}" -gt 75 ]]; then
	T_ICON=""
	T_COLOR="#F8D900"
elif [[ "${TEMP}" -gt 70 ]]; then
	T_ICON=""
	T_COLOR="#E37D00"
elif [[ "${TEMP}" -gt 65 ]]; then
	T_ICON=""
	T_COLOR="#CB4000"
elif [[ "${TEMP}" -gt 55 ]]; then
	T_ICON=""
	T_COLOR="#A11096"
else
	T_ICON=""
	T_COLOR="#7202F3"
fi

echo "<span background=\"#3B0053\"> ${T_ICON} ${TEMP}  </span>"
#echo "<span background=\"#F4C400\" foreground=\"${T_COLOR}\"> ${T_ICON} ${TEMP}  </span>"
#echo "${T_ICON} ${TEMP}"
#echo "${T_COLOR}"

if [[ "${TEMP}" -gt "${URGENT_VALUE}" ]]; then
 exit 33
fi
