#!/bin/bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

INTERFACE="${BLOCK_INSTANCE:-wlan0}"
#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
    [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && exit

#------------------------------------------------------------------------
QUALITY=$(nmcli -f ACTIVE,SIGNAL  device wifi | grep -e 'yes' | awk '{ print int($2 * 100 / 70) }')

#QUALITY=$(awk 'BEGIN { print int( $CURRENTST  * 100 / 70 ) }')
#QUALITY=$(sudo grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

#------------------------------------------------------------------------
WIFICON=" " 
#echo "${WIFICON} ${QUALITY}%" # full text
#echo "${WIFICON} ${QUALITY}%" # full text
# color
if [[ ${QUALITY} -ge 80 ]]; then
    COLOR="#00FF00"
elif [[ ${QUALITY} -lt 80 ]]; then
    COLOR="#FFF600"
elif [[ ${QUALITY} -lt 60 ]]; then
    COLOR="#FFAE00"
elif [[ ${QUALITY} -lt 40 ]]; then
    COLOR="#FF0000"
fi


echo "<span background=\"#53009D\" foreground=\"${COLOR}\">${WIFICON} ${QUALITY}%  </span>" # full text
